### ISSUE TITLE
When I try to query or search for some user shcuelded spaces.

### ISSUE THREAD

**Issue by aalmuarik** [molebox/tweespaces#2]
TypeError: Cannot read property 'data' of undefined
at module.exports (/.npm/_npx/162364/lib/node_modules/tweespaces/utils/find-space.js:30:42)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async .npm/_npx/162364/lib/node_modules/tweespaces/index.js:29:3

**Comment by aalmuarik** [comment]
Thanks
